#!/bin/sh

set -e

echo "Enabling artifice"

ln -s /usr/lib/systemd/system/artificed.service /etc/systemd/system/multi-user.target.wants/

mkdir -p /lib/modules/`uname -r`/kernel
cp /lib/modules/dm_afs.ko /lib/modules/`uname -r`/kernel/
